// Shareable HTML Report
window.KL = window.KL || {};

window.downloadShareableReport = function() {
  if (KL.isLocal) {
    window.location.href = '/api/share-report';
  } else {
    KL.generateClientSideReport();
  }
};

KL.generateClientSideReport = function() {
  var results = KL.state.results;
  if (!results.length) { alert('No results to share.'); return; }
  var total = results.length;
  var passed = KL.state.passedCount;
  var failed = KL.state.failedCount;
  var timeouts = KL.state.timeoutCount;
  var rate = total > 0 ? Math.round((passed / total) * 100) : 0;
  var timestamp = new Date().toLocaleString();

  var rows = results.map(function(r) {
    var loadTime = r.loadTimeMs ? (r.loadTimeMs / 1000).toFixed(1) + 's' : '-';
    var statusColor = r.status === KL.STATUS.PASS ? '#22c55e' : r.status === KL.STATUS.FAIL ? '#ef4444' : '#f59e0b';
    return '<tr><td>' + r.number + '</td><td>' + KL.escHtml(r.title) + '</td><td>' + KL.escHtml(r.section || '') + '</td><td>' + (r.page || '') + '</td><td style="color:' + statusColor + ';font-weight:600">' + r.status + '</td><td>' + loadTime + '</td><td style="color:#888;font-size:0.85em">' + KL.escHtml(r.error || '-') + '</td></tr>';
  }).join('');

  var rateColor = rate >= 100 ? '#22c55e' : rate >= 90 ? '#f59e0b' : '#ef4444';

  var html = '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">' +
    '<title>Kingdomland Video Report</title>' +
    '<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,sans-serif;background:#f1f3fa;color:#080331;line-height:1.5;padding:24px}' +
    '.container{max-width:1200px;margin:0 auto}.header{background:linear-gradient(135deg,#4c6bcd,#080331);color:white;padding:24px 32px;border-radius:12px;margin-bottom:24px}' +
    '.header h1{font-size:1.4rem;margin-bottom:4px}.header p{opacity:0.8;font-size:0.9rem}' +
    '.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:24px}.card{background:white;border-radius:12px;padding:20px;box-shadow:0 1px 3px rgba(0,0,0,0.06)}' +
    '.card-label{font-size:0.8rem;text-transform:uppercase;letter-spacing:0.05em;color:#555;margin-bottom:4px}.card-value{font-size:1.8rem;font-weight:700}' +
    'table{width:100%;border-collapse:collapse;background:white;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.06)}' +
    'th{background:#f8f9fc;text-align:left;padding:10px 14px;font-size:0.78rem;text-transform:uppercase;letter-spacing:0.03em;color:#555;border-bottom:1px solid #e2e6f8}' +
    'td{padding:10px 14px;border-bottom:1px solid #f0f2f8;font-size:0.88rem}tr:hover{background:#f8f9fc}' +
    '.footer{text-align:center;padding:20px;color:#888;font-size:0.8rem;margin-top:24px}' +
    '@media(max-width:768px){.cards{grid-template-columns:repeat(2,1fr)}}</style></head><body><div class="container">' +
    '<div class="header"><h1>Kingdomland Video Checker Report</h1><p>go.kingdomlandkids.com &middot; ' + KL.escHtml(timestamp) + '</p></div>' +
    '<div class="cards">' +
      '<div class="card"><div class="card-label">Total</div><div class="card-value">' + total + '</div></div>' +
      '<div class="card"><div class="card-label">Passed</div><div class="card-value" style="color:#22c55e">' + passed + '</div></div>' +
      '<div class="card"><div class="card-label">Failed</div><div class="card-value" style="color:#ef4444">' + failed + '</div></div>' +
      '<div class="card"><div class="card-label">Timed Out</div><div class="card-value" style="color:#f59e0b">' + timeouts + '</div></div>' +
    '</div>' +
    '<div style="margin-bottom:24px"><div style="font-size:0.9rem;margin-bottom:6px">Pass Rate: <strong>' + rate + '%</strong></div>' +
    '<div style="height:8px;background:#e5e7eb;border-radius:4px;overflow:hidden"><div style="height:100%;width:' + rate + '%;background:' + rateColor + ';border-radius:4px"></div></div></div>' +
    '<table><thead><tr><th>#</th><th>Title</th><th>Section</th><th>Page</th><th>Status</th><th>Load Time</th><th>Error</th></tr></thead><tbody>' + rows + '</tbody></table>' +
    '<div class="footer">Generated by Kingdomland Video Checker</div></div></body></html>';

  var blob = new Blob([html], { type: 'text/html' });
  var a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'video-report-' + Date.now() + '.html';
  a.click();
  URL.revokeObjectURL(a.href);
};
